name: Flutter Tests

on:
  push: 
  pull_request: 

jobs:
  test:
    name: Test on ${{ github.ref_name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get
        working-directory: Flutter

      - name: Run unit tests
        run: flutter test
        working-directory: Flutter
